spring:
  application:
    name: travel_planner_backend
  datasource:
    url: jdbc:postgresql://postgres:5432/travel_planner
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    liquibase:
      enabled: false
jwt:
  secret-key: "dGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIGp3dCB0b2tlbiBnZW5lcmF0aW9u"
  expiration: 86400000
  refresh-expiration: 604800000

server:
  port: 8080